name: Send Scheduled Telegram Messages & Keep Vercel Awake

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes
  workflow_dispatch: # Allows manual execution

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm install
      
      - name: Run scheduler script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node scheduler.js

      - name: Keep Vercel Awake
        run: curl -s "https://tele-bot-rosy.vercel.app/" || echo "Vercel ping failed"
